### ISSUE TITLE
Question on how to use Methods

### ISSUE THREAD

**Issue by schmelto** [larshp/abap-advent-2020-template#123]
Hey,

I have following problem.

![image](https://user-images.githubusercontent.com/30869493/115149428-59e0a380-a064-11eb-9864-e74d832fe57b.png)

Coding:

```abap
 PUBLIC SECTION.

    INTERFACES zif_advent2020_schmelto .

    METHODS part1
      IMPORTING
        !input        TYPE string
      RETURNING
        VALUE(output) TYPE string .
METHOD part1.

"...

  SPLIT input AT |\r\n| INTO TABLE DATA(strings).

  LOOP AT strings INTO DATA(string1).
    LOOP AT strings INTO DATA(string2).
      IF string1 + string2 = 2020.
        DATA(result) = CONV i( string1 * string2 ).
        output = condense( result ).
      ENDIF.
    ENDLOOP.
  ENDLOOP.

ENDMETHOD.

" ...


METHOD zif_advent2020_schmelto~solve.

  output = part1( input ).

ENDMETHOD.
```

with the method call it says in the output `<pending>`

if I add the coding in the solve method it will provide me the right answer.

![image](https://user-images.githubusercontent.com/30869493/115149489-b479ff80-a064-11eb-8705-7200769ffafd.png)

**Comment by larshp** [comment]
yea, there might have been some changes since december

try running "npm ci" instead of "npm install", it should work

I'll have a look into updating the code to latest

**Comment by larshp** [comment]
see changes in https://github.com/larshp/abap-advent-2020/pull/18/commits/658f30d707739eb91ba061cbb5889d14b87b5e56

**Comment by schmelto** [comment]
> see changes in [larshp/abap-advent-2020@658f30d](https://github.com/larshp/abap-advent-2020/commit/658f30d707739eb91ba061cbb5889d14b87b5e56)

with those changes it works fine 🚀 Thanks!

**Comment by larshp** [comment]
things change over time 😄 too much to remember updating everything

but all the old versions are on npm, so it is possible to run old stuff

**Comment by schmelto** [comment]
> things change over time 😄 too much to remember updating everything
> 
> but all the old versions are on npm, so it is possible to run old stuff

yeah but why running it on old stuff when you can get some errors :D

**Comment by larshp** [comment]
bug reports welcome for the transpiler, I'm sure it also gives a lot of errors 😄
