### ISSUE TITLE
Rename to /abc/ namespace

### ISSUE THREAD

**Issue by Ennowulff** [larshp/abap-advent-2020-template#197]
Hey!
I wanted to rename into /abc/-namespace.
my renaming section looks like

`  "rename": {
    "output": "renamed",
    "skip": [],
    "patterns": [{"type": "CLAS|INTF", "oldName": "z(cl|if).", "newName": "/abc/$1_"}]
  },`

which didn't work.

also this regex did not work:

`"patterns": [{"type": "CLAS|INTF", "oldName": "z(cl|if)(.*)", "newName": "/abc/$1$2"}]`

Renaming itself with your settings worked.

`npm run rename` ended with
`abaplint: 213 issue(s) found, 47 file(s) analyzed`
`Renames NOT applied, issues found`

What am I doing wrong?

thanks for any hint.

**Comment by larshp** [comment]
havent checked the code and all for a while, might be broken let me update the dependencies first, sec

plus can you share your exact configuration? open a PR to this repository?

**Comment by Ennowulff** [comment]
see my repo with configuration here https://github.com/inwerken/namespacetest

**Comment by larshp** [comment]
opened a few PRs there

**Comment by Ennowulff** [comment]
Cool! works now. 
thanks @larshp 🤠

**Comment by Ennowulff** [comment]
so it's not possible to rename unless there are any abapLint issues? @larshp

**Comment by larshp** [comment]
there must be zero issues for renaming to work

depending on the situation, its possible to create a new minimal new `abaplint-rename.jsonc` configuration

**Comment by Ennowulff** [comment]
> depending on the situation, its possible to create a new minimal new `abaplint-rename.jsonc` configuration
literally switch anything from "true" to "false" and vice versa?

is it possible to skip blocks?
`    "avoid_use": {
      "exclude": [],
      "severity": "Error",
      "define": true,
      "endselect": true,
      "execSQL": true,
      "kernelCall": true,
      "communication": true,
      "statics": true,
      "systemCall": true,
      "defaultKey": true,
      "break": true,
      "describeLines": true
    },`

to 
`"avoid_use": false;`
?

**Comment by larshp** [comment]
yea, just set it to false, or leave out the rule in the configuration to disable it

`"avoid_use": false,`

**Comment by larshp** [comment]
with https://github.com/abaplint/vscode-abaplint installed use vscode or the web editor to change the configuration, it helps completing and checking the options

https://docs.github.com/en/codespaces/the-githubdev-web-based-editor

![image](https://github.com/larshp/abap-advent-2020-template/assets/5888506/29e1d56d-7bb5-4d77-9d1d-dda7f3630461)
